env:
  CIRRUS_CLONE_DEPTH: 3

task:
  container:
    image: ubuntu:20.04
    cpu: 1
    memory: 512M
  env:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get -qy update
    - apt-get -qy install git php-cli
    - ./regen_html_pages.sh
    - git status
    - test "$(git status --porcelain | wc -l)" -eq 0
    - find . -name '*.php' | xargs -L1 php --syntax-check
